blogs/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name="home"),
    path('newPost', views.newPost, name="newPost"),
    path('get_blogs/', views.get_blogs, name='get_blogs'),
    path('blog_detail/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('blog_delete/<int:blog_id>/', views.delete_post, name='delete_post'),
    path('get_blog_data/<int:blog_id>/', views.get_blog_data, name='get_blog_data'),
    path('get_user_name/', views.get_user_name, name="get_user_name"),
    path('editPost/<int:blog_id>/', views.editPost, name="editPost"),
]

grogBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from blogs.views import *
from grogBlog import settings
from grogBlog.views import login_view, register_view
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('', login_view, name="login_view"),         
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('home/', include('blogs.urls')),
    path('accounts/register/', register_view, name='register_view'),
    path('accounts/login/', login_view, name="login_view")
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogs/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    date = models.DateField("date published")
    content = models.TextField()


class Comments(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    content = models.CharField(max_length=2000)
    date = models.DateTimeField("date published")

blogs/forms.py
# forms.py

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from blogs.models import *

class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
    )

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'author', 'date', 'content']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            'author': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Author'}),
            'date': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Date'}),
            'content': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Content'}),
        }

class CustomRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email', 'password1', 'password2']

blogs/views.py
from datetime import date, datetime
from time import strftime
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from blogs.forms import BlogForm
from .models import Blog, Comments
from django.contrib.staticfiles import finders
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.utils.safestring import mark_safe
from django.core.serializers import serialize


@login_required
def get_blogs(request):
    blogs = Blog.objects.all()

    # Convert blog data to FullCalendar events
    events = []
    for blog in blogs:
        try:
            formatted_date = blog.date.strftime('%Y-%m-%d')
            events.append({
                'title': blog.title,
                'start': formatted_date,  # Format date in 'YYYY-MM-DD'
                'url': 'blog_detail/{}/'.format(blog.id),  # Optional: Add a URL for event click
            })
        except Exception as e:
            print(f"Error processing blog {blog.id}: {e}")

    # Return events as JSON response
    return JsonResponse(events, safe=False)
    

@login_required
def get_blog_data(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)

    if request.method == 'POST':
        # Update the blog post with the submitted data
        blog.title = request.POST.get('title', '')
        blog.author = request.POST.get('author', '')
        blog.date = datetime.datetime.strptime(request.POST.get('date', ''), '%Y-%m-%d') - 1
        blog.content = request.POST.get('content', '')
        blog.save()

        return JsonResponse({'status': 'success'})
    else:
        # Return the current blog data for editing
        data = {
            'title': blog.title,
            'author': blog.author,
            'date': blog.date.strftime('%Y-%m-%d'),
            'content': blog.content,
        }
        return JsonResponse(data)

@login_required
def delete_post(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    blog.delete()
    return redirect('blogs:home')



@login_required
def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blogPost.html', {'blog': blog})


@login_required
def get_user_name(request):
    user = request.user
    data = {
        'user': user.username
    }
    return JsonResponse(data)




@login_required
def index(request):
    blogList = Blog.objects.order_by('-date')
    time = strftime('%c')
    
    return render(request, "home.html", {'time': time, 'blogs': blogList})

@login_required
def newPost(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blogs:home')
        print(form.errors)
    else:
        form = BlogForm()
    return render(request, 'home.html', {'form': form})



def editPost(request, blog_id):
    # Retrieve the existing blog post based on blog_id
    blog_post = get_object_or_404(Blog, pk=blog_id)

    if request.method == "POST":
        # Populate the form with the existing blog post data
        form = BlogForm(request.POST, instance=blog_post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user.username
            post.save()
            return redirect('blogs:home')
        print(form.errors)
    else:
        # Populate the form with the existing blog post data
        form = BlogForm(instance=blog_post)

    return render(request, 'home.html', {'form': form})


def custom_css(request):
    css_path = finders.find('blogs/style.css')

    if css_path:
        with open(css_path, 'r') as css_file:
            css_content = css_file.read()

        response = HttpResponse(css_content, content_type='text/css')
        return response
    else:
        return HttpResponse(status=404)

grogBlog/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model, login
from blogs.forms import CustomRegistrationForm, CustomLoginForm  # Import your custom form here
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings  # Import settings module

User = get_user_model()

def register_view(request):
    form = CustomRegistrationForm()
    if request.method == 'POST':
        form = CustomRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login_view')
    
    return render(request, 'registration/registration.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = CustomLoginForm(request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect(settings.LOGIN_REDIRECT_URL)  # Use settings.LOGIN_REDIRECT_URL
    else:
        form = CustomLoginForm()

    return render(request, 'registration/login.html', {'form': form})

blogs/templates/base.html
{% load static %}

<html>
  <head>
    <meta charset="utf-8" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="{% static 'blogs/style.css' %}" />
    <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.10/index.global.min.js"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function () {
        var calendarEl = document.getElementById("calendar");
        var calendar = new FullCalendar.Calendar(calendarEl, {
          events: "{% url 'blogs:get_blogs' %}",
          timeZone: "America/Denver",
          initialView: "dayGridMonth",
          height: "85%", // Set to your desired height (e.g., 90%)
          dayHeaderClassNames: function (day) {
            return "custom-weekday-label";
          },
          windowResize: function (view) {
            // Adjust the calendar height after window resize
            adjustCalendarHeight();
          },
        });

        function adjustCalendarHeight() {
          calendarEl.style.width = "100%";
          calendarEl.style.height = "90%"; // Set to your desired height (e.g., 90%)
        }

        // Initial adjustment
        adjustCalendarHeight();
        calendar.render();
      });
    </script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  </head>
  <body>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

blogs/templates/blogPost.html
{% extends 'base.html' %} {% load markdown_filters %}
<!--prettier-ignore -->
{% load static %}{% block title %}Home{% endblock %}

<!-- prettier-ignore -->
{% block content %}

<body class="home-body">
  <div class="header-container">
    <div class="navbar">Grog Blog</div>
    <a href="{% url 'blogs:home' %}">
      <button class="createButton">Back to Calendar</button>
    </a>
    <div class="greeting">
      {% if user.is_authenticated %} Hi {{ user.first_name }}!
      <p><a href="{% url 'logout' %}">Log Out</a></p>
      {% else %}
      <p>You are not logged in</p>
      <a href="{% url 'login' %}">Log In</a>
      {% endif %}
    </div>
  </div>
  <div class="blog-post">
    <div class="header">
      <h2 style="margin-bottom: 0%">{{ blog.title }}</h2>
      <p class="date">Date: {{ blog.date|date:"F j, Y" }}</p>
    </div>
    <div class="header">
      <p class="author">Author: {{ blog.author }}</p>
      <div>
        {% if user.is_superuser %}
                <a
                href="#"
                class="edit-post-btn"
                data-toggle="modal"
                data-target="#createPostModal"
                data-blog-id="{{ blog.id }}"
            >
                <button class="edit-post-btn btn btn-dark mb-3" type="button">Edit</button>
            </a>
            <a href="{% url 'blogs:delete_post' blog_id=blog.id %}">
                <button class="btn btn-danger mb-3" type="button">Delete</button>
            </a>
        {% endif %}
      </div>
    </div>
    <div class="border"></div>
    <div class="content">
        {{ blog.content|markdown|safe }}
    </div>
  </div>
   <div
    class="modal fade"
    id="createPostModal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="createPostModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="createPostModalLabel">Edit Post</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <!-- Example form for creating a post -->
          <form method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_title">Title:</label>
              <input
                type="text"
                class="form-control"
                id="id_title"
                name="title"
                required
              />
            </div>
            <div class="form-group">
              <label for="id_author">Author:</label>
              <input
                type="text"
                class="form-control"
                id="id_author"
                name="author"
                required
                readonly
              />
            </div>
            <div class="form-group">
              <label for="id_date">Date:</label>
              <textarea
                class="form-control"
                style="text-align: center;"
                id="id_date"
                name="date"
                required
                readonly
              ></textarea>
            </div>
            <div class="form-group">
              <label for="id_content">Content:</label>
              <textarea
                class="form-control"
                id="id_content"
                name="content"
                rows="3"
                required
              ></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Edit Post</button>
          </form>
        </div>
      </div>
</body>
<script>
    var blogId;  // Declare blogId as a global variable
  
    // Function to fetch and display existing blog content
    function fetchBlogDataAndDisplay() {
      // Assuming you have an API endpoint for retrieving blog details
      var apiUrl = "{% url 'blogs:get_blog_data' blog_id=blog.id %}";
  
      // Make an AJAX request to fetch blog details
      $.ajax({
        url: apiUrl,
        method: 'GET',
        success: function (data) {
          // Populate the form fields with retrieved data
          $('#id_title').val(data.title);
          $('#id_author').val(data.author);
          $('#id_date').val(data.date);
          $('#id_content').val(data.content);
  
          // Show the modal after fetching and displaying blog content
          $('#createPostModal').modal('show');
        },
        error: function () {
          console.log('Error fetching blog details');
        }
      });
    }
  
    // Assuming you have a button with class 'edit-post-btn' to trigger the modal
    $('.edit-post-btn').click(function () {
      blogId = $(this).data('blog-id');  // Update the global blogId variable
  
      // Fetch and display existing blog content
      fetchBlogDataAndDisplay();
    });
  
    // Function to handle form submission and update blog post
    $('#createPostModal').find('form').submit(function (e) {
      e.preventDefault(); // Prevent the default form submission
  
      // Assuming you have an API endpoint for retrieving and updating blog details
      var apiUrl = "{% url 'blogs:editPost' blog_id=blog.id %}";
  
      // Make an AJAX request to fetch and update blog details
      $.ajax({
        url: apiUrl,
        method: 'POST',
        data: $(this).serialize(),
        success: function (data) {
            $('#createPostModal').modal('hide');
            updateDisplayedContent(data);
        },
      });
    });
  
    // Function to update the displayed content on success
    function updateDisplayedContent(data) {
      // Update the displayed content on the page using data received in the response
      // Adjust this part based on your actual HTML structure and how you want to update the content
      $('#blog-title').text(data.title);
      $('#blog-author').text('Author: ' + data.author);
      $('#blog-date').text('Date: ' + data.date);
      $('#blog-content').html(data.content);

      location.reload();
    }
  
    // Run this when the document is ready
    $(document).ready(function () {
      // Assuming there is a blog ID available, you can fetch and display content immediately
      if (blogId) {
        fetchBlogDataAndDisplay();
      }
    });
  </script>
  
  

{% endblock %}

blogs/templates/home.html
{% extends "base.html" %}

<!--prettier-ignore -->
{% load static %}{% block title %}Home{% endblock %}

<!-- prettier-ignore -->
{% block content %}
<script>
  document.addEventListener("DOMContentLoaded", function () {
    var dateTextarea = document.getElementById("id_date");
    var authorTextarea = document.getElementById("id_author");

    if (dateTextarea) {
      // Get current date in YYYY-MM-DD format
      // Get the current date
      var currentDate = new Date();

      // Subtract one day from the current date
      currentDate.setDate(currentDate.getDate());

      // Format the date to ISO string (YYYY-MM-DD)
      var mtcDate = currentDate.toISOString().split("T")[0];
      console.log(currentDate);

      dateTextarea.value = mtcDate;
    }
  });
  var apiUrl = "{% url 'blogs:get_user_name' %}";

  // Make an AJAX request to fetch the username
  $.ajax({
    url: apiUrl,
    method: "GET",
    success: function (data) {
      var authorTextarea = document.getElementById("id_author");

      if (authorTextarea && data.user) {
        // Set the value of the textarea to the fetched username
        authorTextarea.value = data.user;
      }
    },
    error: function () {
      console.log("Error fetching username");
    },
  });
</script>
<body class="home-body">
  <div class="header-container">
    <div class="navbar">Grog Blog</div>
    {% if user.is_superuser %}
    <a>
      <button
        class="createButton"
        data-toggle="modal"
        data-target="#createPostModal"
      >
        Create Post
      </button>
    </a>
    {% endif %}
    <div class="greeting">
      {% if user.is_authenticated %} Hi {{ user.first_name }}!
      <p><a href="{% url 'logout' %}">Log Out</a></p>
      {% else %}
      <p>You are not logged in</p>
      <a href="{% url 'login' %}">Log In</a>
      {% endif %}
    </div>
  </div>
  <div id="calendar"></div>
  <!-- Modal -->
  <div
    class="modal fade"
    id="createPostModal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="createPostModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="createPostModalLabel">Create Post</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <!-- Example form for creating a post -->
          <form method="POST" action="{% url 'blogs:newPost' %}">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_title">Title:</label>
              <input
                type="text"
                class="form-control"
                id="id_title"
                name="title"
                required
              />
            </div>
            <div class="form-group">
              <label for="id_author">Author:</label>
              <input
                type="text"
                class="form-control"
                id="id_author"
                name="author"
                required
                readonly
              />
            </div>
            <div class="form-group">
              <label for="id_date">Date:</label>
              <textarea
                style="text-align: center"
                class="form-control"
                id="id_date"
                name="date"
                required
                readonly
              ></textarea>
            </div>
            <div class="form-group">
              <label for="id_content">Content:</label>
              <textarea
                class="form-control"
                id="id_content"
                name="content"
                rows="3"
                required
              ></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Create Post</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}